#服务配置
server:
  port: 8686
  tomcat:
    uri-encoding: UTF-8

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
logging:
  path: classpath:log4j2.xml

